### PR TITLE
Update nvm-telescope-fzf build command

### PR DESCRIPTION
**Pull request by tmysl**
Update the build command for nvm-telescope-fzf to match upstream docs and configs documented in https://github.com/nvim-telescope/telescope-fzf-native.nvim#installation docs

### CODE REVIEW

**Comment by tmysl** [comment]
image

**Comment by briandipalma** [comment]
Surely all you need to do to fix the original error is install make? I'm guessing you already had cmake installed?

**Comment by briandipalma** [comment]
https://github.com/LazyVim/LazyVim/issues/2132

**Comment by folke** [comment]
fzf-native now checks for both make and cmake. We still prefer cmake.

https://github.com/LazyVim/LazyVim/commit/1c13a5c10b745f741ebbb08d3963862e9d4e307e

upstream docs also have the `make` as the build command, so it's not that we did that differently.

**Comment by folke** [comment]
Wrong repo :)

I actually removed that part from the examples, since `telescope-fzf-native` is now included in LazyVim by default.
https://github.com/LazyVim/starter/commit/914c60ae75cdf61bf77434d2ad2fbf775efd963b

**Pull request closed without merging**
